# /// script
# requires-python = ">=3.11,<=3.13"
# dependencies = [
#     "mteb",
#     "pillow",
#     "pyvespa @ file:///${PROJECT_ROOT}",
#     "simplejson",
# ]
# ///
from pathlib import Path

from vespa.vespa_mteb import VespaMTEBApp, VespaMTEBEvaluator
from vespa.models import ModelConfig

model_config_dict: dict[str, list[ModelConfig]] = {
    "nomic-ai-modernbert": [
        ModelConfig(
            model_id="nomic-ai-modernbert",
            embedding_dim=768,
            binarized=True,
            distance_metric="hamming",
            model_url="https://huggingface.co/nomic-ai/modernbert-embed-base/resolve/main/onnx/model.onnx",
            tokenizer_url="https://huggingface.co/nomic-ai/modernbert-embed-base/resolve/main/tokenizer.json",
            max_tokens=8192,
            transformer_output="token_embeddings",
            query_prepend="search_query: ",
            document_prepend="search_document: ",
        ),
        ModelConfig(
            model_id="nomic-ai-modernbert",
            embedding_dim=768,
            binarized=False,
            embedding_field_type="float",
            distance_metric="angular",
            model_url="https://huggingface.co/nomic-ai/modernbert-embed-base/resolve/main/onnx/model.onnx",
            tokenizer_url="https://huggingface.co/nomic-ai/modernbert-embed-base/resolve/main/tokenizer.json",
            max_tokens=8192,
            transformer_output="token_embeddings",
            query_prepend="search_query: ",
            document_prepend="search_document: ",
        ),
        ModelConfig(
            model_id="nomic-ai-modernbert",
            embedding_dim=768,
            binarized=False,
            embedding_field_type="bfloat16",
            distance_metric="angular",
            model_url="https://huggingface.co/nomic-ai/modernbert-embed-base/resolve/main/onnx/model.onnx",
            tokenizer_url="https://huggingface.co/nomic-ai/modernbert-embed-base/resolve/main/tokenizer.json",
            max_tokens=8192,
            transformer_output="token_embeddings",
            query_prepend="search_query: ",
            document_prepend="search_document: ",
        ),
    ],
    "lightonai-modernbert-large": [
        ModelConfig(
            model_id="lightonai-modernbert-large",
            embedding_dim=1024,
            binarized=True,
            distance_metric="hamming",
            model_url="https://huggingface.co/lightonai/modernbert-embed-large/resolve/main/onnx/model.onnx",
            tokenizer_url="https://huggingface.co/lightonai/modernbert-embed-large/resolve/main/tokenizer.json",
            max_tokens=8192,
            query_prepend="search_query: ",
            document_prepend="search_document: ",
        ),
        ModelConfig(
            model_id="lightonai-modernbert-large",
            embedding_dim=1024,
            binarized=False,
            embedding_field_type="float",
            distance_metric="angular",
            model_url="https://huggingface.co/lightonai/modernbert-embed-large/resolve/main/onnx/model.onnx",
            tokenizer_url="https://huggingface.co/lightonai/modernbert-embed-large/resolve/main/tokenizer.json",
            max_tokens=8192,
            query_prepend="search_query: ",
            document_prepend="search_document: ",
        ),
        ModelConfig(
            model_id="lightonai-modernbert-large",
            embedding_dim=1024,
            binarized=False,
            embedding_field_type="bfloat16",
            distance_metric="angular",
            model_url="https://huggingface.co/lightonai/modernbert-embed-large/resolve/main/onnx/model.onnx",
            tokenizer_url="https://huggingface.co/lightonai/modernbert-embed-large/resolve/main/tokenizer.json",
            max_tokens=8192,
            query_prepend="search_query: ",
            document_prepend="search_document: ",
        ),
    ],
    "alibaba-gte-modernbert": [
        ModelConfig(
            model_id="alibaba-gte-modernbert",
            embedding_dim=768,
            binarized=True,
            distance_metric="hamming",
            model_url="https://huggingface.co/Alibaba-NLP/gte-modernbert-base/resolve/main/onnx/model.onnx",
            tokenizer_url="https://huggingface.co/Alibaba-NLP/gte-modernbert-base/resolve/main/tokenizer.json",
            max_tokens=8192,
            pooling_strategy="cls",
        ),
        ModelConfig(
            model_id="alibaba-gte-modernbert",
            embedding_dim=768,
            binarized=False,
            embedding_field_type="float",
            distance_metric="angular",
            model_url="https://huggingface.co/Alibaba-NLP/gte-modernbert-base/resolve/main/onnx/model.onnx",
            tokenizer_url="https://huggingface.co/Alibaba-NLP/gte-modernbert-base/resolve/main/tokenizer.json",
            max_tokens=8192,
            pooling_strategy="cls",
        ),
        ModelConfig(
            model_id="alibaba-gte-modernbert",
            embedding_dim=768,
            binarized=False,
            embedding_field_type="bfloat16",
            distance_metric="angular",
            model_url="https://huggingface.co/Alibaba-NLP/gte-modernbert-base/resolve/main/onnx/model.onnx",
            tokenizer_url="https://huggingface.co/Alibaba-NLP/gte-modernbert-base/resolve/main/tokenizer.json",
            max_tokens=8192,
            pooling_strategy="cls",
        ),
    ],
    "e5-small-v2": [
        ModelConfig(
            model_id="e5-small-v2",
            embedding_dim=384,
            binarized=True,
            distance_metric="hamming",
            model_url="https://huggingface.co/intfloat/e5-small-v2/resolve/main/onnx/model.onnx",
            tokenizer_url="https://huggingface.co/intfloat/e5-small-v2/resolve/main/tokenizer.json",
            max_tokens=512,
            query_prepend="query: ",
            document_prepend="passage: ",
        ),
        ModelConfig(
            model_id="e5-small-v2",
            embedding_dim=384,
            binarized=False,
            embedding_field_type="float",
            distance_metric="angular",
            model_url="https://huggingface.co/intfloat/e5-small-v2/resolve/main/onnx/model.onnx",
            tokenizer_url="https://huggingface.co/intfloat/e5-small-v2/resolve/main/tokenizer.json",
            max_tokens=512,
            query_prepend="query: ",
            document_prepend="passage: ",
        ),
        ModelConfig(
            model_id="e5-small-v2",
            embedding_dim=384,
            binarized=False,
            embedding_field_type="bfloat16",
            distance_metric="angular",
            model_url="https://huggingface.co/intfloat/e5-small-v2/resolve/main/onnx/model.onnx",
            tokenizer_url="https://huggingface.co/intfloat/e5-small-v2/resolve/main/tokenizer.json",
            max_tokens=512,
            query_prepend="query: ",
            document_prepend="passage: ",
        ),
    ],
    "e5-base-v2": [
        ModelConfig(
            model_id="e5-base-v2",
            embedding_dim=768,
            binarized=True,
            distance_metric="hamming",
            model_url="https://huggingface.co/intfloat/e5-base-v2/resolve/main/onnx/model.onnx",
            tokenizer_url="https://huggingface.co/intfloat/e5-base-v2/resolve/main/tokenizer.json",
            max_tokens=512,
            query_prepend="query: ",
            document_prepend="passage: ",
        ),
        ModelConfig(
            model_id="e5-base-v2",
            embedding_dim=768,
            binarized=False,
            embedding_field_type="float",
            distance_metric="angular",
            model_url="https://huggingface.co/intfloat/e5-base-v2/resolve/main/onnx/model.onnx",
            tokenizer_url="https://huggingface.co/intfloat/e5-base-v2/resolve/main/tokenizer.json",
            max_tokens=512,
            query_prepend="query: ",
            document_prepend="passage: ",
        ),
        ModelConfig(
            model_id="e5-base-v2",
            embedding_dim=768,
            binarized=False,
            embedding_field_type="bfloat16",
            distance_metric="angular",
            model_url="https://huggingface.co/intfloat/e5-base-v2/resolve/main/onnx/model.onnx",
            tokenizer_url="https://huggingface.co/intfloat/e5-base-v2/resolve/main/tokenizer.json",
            max_tokens=512,
            query_prepend="query: ",
            document_prepend="passage: ",
        ),
    ],
    "e5-large-v2": [
        ModelConfig(
            model_id="e5-large-v2",
            embedding_dim=1024,
            binarized=True,
            distance_metric="hamming",
            model_url="https://huggingface.co/intfloat/e5-large-v2/resolve/main/onnx/model.onnx",
            tokenizer_url="https://huggingface.co/intfloat/e5-large-v2/resolve/main/tokenizer.json",
            max_tokens=512,
            query_prepend="query: ",
            document_prepend="passage: ",
        ),
        ModelConfig(
            model_id="e5-large-v2",
            embedding_dim=1024,
            binarized=False,
            embedding_field_type="float",
            distance_metric="angular",
            model_url="https://huggingface.co/intfloat/e5-large-v2/resolve/main/onnx/model.onnx",
            tokenizer_url="https://huggingface.co/intfloat/e5-large-v2/resolve/main/tokenizer.json",
            max_tokens=512,
            query_prepend="query: ",
            document_prepend="passage: ",
        ),
        ModelConfig(
            model_id="e5-large-v2",
            embedding_dim=1024,
            binarized=False,
            embedding_field_type="bfloat16",
            distance_metric="angular",
            model_url="https://huggingface.co/intfloat/e5-large-v2/resolve/main/onnx/model.onnx",
            tokenizer_url="https://huggingface.co/intfloat/e5-large-v2/resolve/main/tokenizer.json",
            max_tokens=512,
            query_prepend="query: ",
            document_prepend="passage: ",
        ),
    ],
    "multilingual-e5-base": [
        ModelConfig(
            model_id="multilingual-e5-base",
            embedding_dim=768,
            binarized=True,
            distance_metric="hamming",
            model_url="https://huggingface.co/intfloat/multilingual-e5-base/resolve/main/onnx/model.onnx",
            tokenizer_url="https://huggingface.co/intfloat/multilingual-e5-base/resolve/main/tokenizer.json",
            max_tokens=512,
            query_prepend="query: ",
            document_prepend="passage: ",
        ),
        ModelConfig(
            model_id="multilingual-e5-base",
            embedding_dim=768,
            binarized=False,
            embedding_field_type="float",
            distance_metric="angular",
            model_url="https://huggingface.co/intfloat/multilingual-e5-base/resolve/main/onnx/model.onnx",
            tokenizer_url="https://huggingface.co/intfloat/multilingual-e5-base/resolve/main/tokenizer.json",
            max_tokens=512,
            query_prepend="query: ",
            document_prepend="passage: ",
        ),
        ModelConfig(
            model_id="multilingual-e5-base",
            embedding_dim=768,
            binarized=False,
            embedding_field_type="bfloat16",
            distance_metric="angular",
            model_url="https://huggingface.co/intfloat/multilingual-e5-base/resolve/main/onnx/model.onnx",
            tokenizer_url="https://huggingface.co/intfloat/multilingual-e5-base/resolve/main/tokenizer.json",
            max_tokens=512,
            query_prepend="query: ",
            document_prepend="passage: ",
        ),
    ],
}

if __name__ == "__main__":
    # Create results dir as home dir / results. Create if it does not exist
    results_dir = Path.home() / "results"
    results_dir.mkdir(parents=True, exist_ok=True)

    for model_name, model_configs in model_config_dict.items():

        # Create and run the evaluator
        evaluator = VespaMTEBEvaluator(
            model_configs=model_configs,
            benchmark_name="NanoBEIR",
            results_dir=results_dir,
            overwrite=True,
        )

        results = evaluator.evaluate()