# pytest.ini
[pytest]
pythonpath = .
markers =
    performance: performance tests of pyvespa and k6 against a Vespa Cloud instance
    performance_last: performance test that must run after all other performance tests in the session
