# Copyright Vespa.ai. Licensed under the terms of the Apache 2.0 license. See LICENSE in the project root.

shared:
  image: quay.io/centos/centos:stream8
  annotations:
    screwdriver.cd/restrictPR: fork
  environment:
    PYVESPA_VERSION: 0.7
jobs:
  unit-tests:
    requires: [~commit,~pr]
    annotations:
      screwdriver.cd/timeout: 120
      screwdriver.cd/cpu: HIGH
      screwdriver.cd/ram: HIGH
      screwdriver.cd/dockerEnabled: true
      screwdriver.cd/dockerCpu: TURBO
      screwdriver.cd/dockerRam: TURBO
      screwdriver.cd/buildPeriodically: H 11 * * *
    steps:
      - setup: |
          export WORK_DIR=$SD_DIND_SHARE_PATH
          export RESOURCES_DIR=$(pwd)/vespa/resources
      - install-docker: |
          dnf install -y dnf-plugins-core
          dnf config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
          dnf install -y docker-ce-cli
          docker system info
          ls -la $SD_DIND_SHARE_PATH
      - install-python: |
          dnf install -y python38-pip python38-devel gcc gcc-c++ # gcc et al required for pytrec_eval
          dnf install -y --enablerepo=powertools pandoc
          python3 -m pip install --upgrade pip
          python3 -m pip install -e .[dev]
          python3 -m pip install -r docs/sphinx/source/requirements.txt
          python3 -m pip install -r docs/sphinx/source/notebook_requirements.txt
      - run-doc-linkcheck: |
          sphinx-build -E -D exclude_patterns=getting-started-pyvespa-cloud.ipynb -b linkcheck docs/sphinx/source docs/sphinx/build
          sphinx-build -E -D exclude_patterns=getting-started-pyvespa-cloud.ipynb docs/sphinx/source docs/sphinx/build
          rm -fr docs/sphinx/build
      - run-doc-tests: |
          pytest vespa --doctest-modules
      - run-unit-tests: |
          pytest tests/unit

  integration-except-cloud:
    requires: [~commit,~pr]
    annotations:
      screwdriver.cd/timeout: 120
      screwdriver.cd/cpu: HIGH
      screwdriver.cd/ram: HIGH
      screwdriver.cd/dockerEnabled: true
      screwdriver.cd/dockerCpu: TURBO
      screwdriver.cd/dockerRam: TURBO
      screwdriver.cd/buildPeriodically: H 11 * * *
    steps:
      - setup: |
          export WORK_DIR=$SD_DIND_SHARE_PATH
          export RESOURCES_DIR=$(pwd)/vespa/resources
      - install-docker: |
          dnf install -y dnf-plugins-core
          dnf config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
          dnf install -y docker-ce-cli
          docker system info
          ls -la $SD_DIND_SHARE_PATH
      - install-python: |
          dnf install -y python38-pip
          python3 -m pip install --upgrade pip
          python3 -m pip install -e .[dev]
      - run-integration-docker: |
          pytest tests/integration/test_integration_docker.py -s -v

  notebooks-except-cloud:
    requires: [~commit,~pr]
    annotations:
      screwdriver.cd/timeout: 120
      screwdriver.cd/cpu: HIGH
      screwdriver.cd/ram: HIGH
      screwdriver.cd/dockerEnabled: true
      screwdriver.cd/dockerCpu: TURBO
      screwdriver.cd/dockerRam: TURBO
      screwdriver.cd/buildPeriodically: H 11 * * *
    steps:
      - setup: |
          dnf install -y git
          export WORK_DIR=$SD_DIND_SHARE_PATH
          export RESOURCES_DIR=$(pwd)/vespa/resources
      - install-docker: |
          dnf install -y dnf-plugins-core
          dnf config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
          dnf install -y docker-ce-cli
          docker system info
          ls -la $SD_DIND_SHARE_PATH
      - install-python: |
          dnf install -y python38-pip python38-devel gcc gcc-c++ # gcc required for pytrec_eval
          python3 -m pip install --upgrade pip
          python3 -m pip install -e .[dev]
          python3 -m pip install -r docs/sphinx/source/requirements.txt
          python3 -m pip install -r docs/sphinx/source/notebook_requirements.txt
      - install-vespa-cli: |
          VESPA_CLI_VERSION=$(curl -fsSL https://api.github.com/repos/vespa-engine/vespa/releases/latest | grep -Po '"tag_name": "v\K.*?(?=")') && \
          curl -fsSL https://github.com/vespa-engine/vespa/releases/download/v${VESPA_CLI_VERSION}/vespa-cli_${VESPA_CLI_VERSION}_linux_amd64.tar.gz | tar -zxf - -C /opt && \
          ln -sf /opt/vespa-cli_${VESPA_CLI_VERSION}_linux_amd64/bin/vespa /usr/local/bin/
      - install-openmp: |
          # required for using lightgbm
          dnf install -y libgomp zstd
      - run-notebooks-except-cloud-related: |
          #
          # Exclude non-testable notebooks below
          #
          dnf install -y tree
          echo "All non-cloud notebooks:"

          find docs -name '*.ipynb' ! -name '*cloud*.ipynb' | while read f
          do
            echo "running: runnb --allow-not-trusted $f"
            runnb --allow-not-trusted $f
            if [ $? -ne 0 ]
            then
              exit 1
            fi
          done

  integration-cloud:
    requires: [~commit]
    annotations:
      screwdriver.cd/timeout: 120
      screwdriver.cd/cpu: HIGH
      screwdriver.cd/ram: HIGH
      screwdriver.cd/buildPeriodically: H 11 * * *
    secrets:
      - VESPA_TEAM_API_KEY
    environment:
      SD_ZIP_ARTIFACTS: true
    steps:
      - setup: |
          export WORK_DIR=$SD_DIND_SHARE_PATH
          export RESOURCES_DIR=$(pwd)/vespa/resources
      - install-python: |
          dnf install -y python38-pip
          python3 -m pip install --upgrade pip
          python3 -m pip install -e .[dev]
      - run-integration-cloud: |
          pytest tests/integration/test_integration_vespa_cloud.py -s -v

  integration-cloud-token:
    requires: [~commit]
    annotations:
      screwdriver.cd/timeout: 120
      screwdriver.cd/cpu: HIGH
      screwdriver.cd/ram: HIGH
      screwdriver.cd/buildPeriodically: H 11 * * *
    secrets:
      - VESPA_TEAM_API_KEY
      - VESPA_CLOUD_SECRET_TOKEN
    environment:
      SD_ZIP_ARTIFACTS: true
    steps:
      - setup: |
          export WORK_DIR=$SD_DIND_SHARE_PATH
          export RESOURCES_DIR=$(pwd)/vespa/resources
      - install-python: |
          dnf install -y python38-pip
          python3 -m pip install --upgrade pip
          python3 -m pip install -e .[dev]
      - run-integration-cloud: |
          pytest tests/integration/test_integration_vespa_cloud_token.py -s -v

  integration-cloud-vector-search:
    requires: [~commit]
    annotations:
      screwdriver.cd/timeout: 120
      screwdriver.cd/cpu: HIGH
      screwdriver.cd/ram: HIGH
      screwdriver.cd/buildPeriodically: H 11 * * *
    secrets:
      - VESPA_TEAM_API_KEY
      - VESPA_CLOUD_SECRET_TOKEN
    environment:
      SD_ZIP_ARTIFACTS: true
    steps:
      - setup: |
          export WORK_DIR=$SD_DIND_SHARE_PATH
          export RESOURCES_DIR=$(pwd)/vespa/resources
      - install-python: |
          dnf install -y python38-pip
          python3 -m pip install --upgrade pip
          python3 -m pip install -e .[dev]
      - run-integration-cloud: |
          pytest tests/integration/test_integration_vespa_cloud_vector_search.py -s -v

  notebooks-cloud:
    requires: [integration-cloud]
    annotations:
      screwdriver.cd/timeout: 120
      screwdriver.cd/cpu: HIGH
      screwdriver.cd/ram: HIGH
    secrets:
      - VESPA_TEAM_API_KEY
      - OPENAI_API_KEY
      - CO_API_KEY
    environment:
      SD_ZIP_ARTIFACTS: true
    steps:
      - setup: |
          export WORK_DIR=$SD_DIND_SHARE_PATH
          export RESOURCES_DIR=$(pwd)/vespa/resources
      - install-python: |
          dnf install -y which git-all python38-pip gcc python38-devel gcc-c++ # gcc required for pytrec_eval
          python3 -m pip install --upgrade pip
          python3 -m pip install -e .[dev]
          python3 -m pip install -r docs/sphinx/source/requirements.txt
          python3 -m pip install -r docs/sphinx/source/notebook_requirements.txt
      - install-vespa-cli: |
          VESPA_CLI_VERSION=$(curl -fsSL https://api.github.com/repos/vespa-engine/vespa/releases/latest | grep -Po '"tag_name": "v\K.*?(?=")') && \
          curl -fsSL https://github.com/vespa-engine/vespa/releases/download/v${VESPA_CLI_VERSION}/vespa-cli_${VESPA_CLI_VERSION}_linux_amd64.tar.gz | tar -zxf - -C /opt && \
          ln -sf /opt/vespa-cli_${VESPA_CLI_VERSION}_linux_amd64/bin/vespa /usr/local/bin/
      - run-notebooks-cloud-related: |
          echo "PATH:"
          echo $PATH
          find docs -name '*cloud*.ipynb' -not -name mother-of-all-embedding-models-cloud.ipynb | while read f
          do
            echo "running: runnb --allow-not-trusted $f"
            runnb --allow-not-trusted $f
            if [ $? -ne 0 ]
            then
              exit 1
            fi
          done
