shared:
  image: quay.io/centos/centos:stream8
  environment:
    PYVESPA_VERSION: 0.7
jobs:
  unit-tests:
    requires: [~commit,~pr]
    annotations:
      screwdriver.cd/timeout: 120
      screwdriver.cd/cpu: HIGH
      screwdriver.cd/ram: HIGH
      screwdriver.cd/buildPeriodically: H 11 * * *
    steps:
      - setup: |
          echo DONE
  integration-except-cloud:
    requires: [~commit,~pr]
    annotations:
      screwdriver.cd/timeout: 120
      screwdriver.cd/cpu: HIGH
      screwdriver.cd/ram: HIGH
      screwdriver.cd/dockerEnabled: true
      screwdriver.cd/dockerCpu: TURBO
      screwdriver.cd/dockerRam: TURBO
      screwdriver.cd/buildPeriodically: H 11 * * *
    steps:
      - setup: |
          echo DONE
  notebooks-except-cloud:
    requires: [~commit,~pr]
    annotations:
      screwdriver.cd/timeout: 120
      screwdriver.cd/cpu: HIGH
      screwdriver.cd/ram: HIGH
      screwdriver.cd/dockerEnabled: true
      screwdriver.cd/dockerCpu: TURBO
      screwdriver.cd/dockerRam: TURBO
      screwdriver.cd/buildPeriodically: H 11 * * *
    steps:
      - setup: |
          dnf install -y git
          export WORK_DIR=$SD_DIND_SHARE_PATH
          export RESOURCES_DIR=$(pwd)/vespa/resources
          #export PYVESPA_DEBUG=true
      - install-docker: |
          dnf install -y dnf-plugins-core
          dnf config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
          dnf install -y docker-ce-cli
          docker system info
          ls -la $SD_DIND_SHARE_PATH
      - install-python: |
          dnf install -y python38-pip
          python3 -m pip install --upgrade pip
          python3 -m pip install pytest notebook nbconvert runnb
          python3 -m pip install -e .[full]
          python3 -m pip install -r docs/sphinx/source/requirements.txt
          python3 -m pip install -r docs/sphinx/source/notebook_requirements.txt
      - run-notebooks-except-cloud-related: |
          set -e
          dnf install -y tree wget
          find docs -name '*.ipynb' ! -name '*cloud*.ipynb'
          runnb --allow-not-trusted docs/sphinx/source/use_cases/image_search/image-search-scratch.ipynb
  integration-cloud:
    requires: [~commit]
    annotations:
      screwdriver.cd/timeout: 120
      screwdriver.cd/cpu: HIGH
      screwdriver.cd/ram: HIGH
      screwdriver.cd/buildPeriodically: H 11 * * *
    secrets:
      - VESPA_CLOUD_USER_KEY
    environment:
      SD_ZIP_ARTIFACTS: true
    steps:
      - setup: |
          echo DONE
  notebooks-cloud:
    requires: [integration-cloud]
    annotations:
      screwdriver.cd/timeout: 120
      screwdriver.cd/cpu: HIGH
      screwdriver.cd/ram: HIGH
    secrets:
      - VESPA_CLOUD_USER_KEY
    environment:
      SD_ZIP_ARTIFACTS: true
    steps:
      - setup: |
          echo DONE
  deploy-test-server:
    requires: [unit-tests, integration-except-cloud, notebooks-except-cloud, notebooks-cloud]
    annotations:
      screwdriver.cd/timeout: 120
      screwdriver.cd/cpu: HIGH
      screwdriver.cd/ram: HIGH
    secrets:
      - TEST_PYPI_TOKEN
    steps:
      - install-python: |
          echo DONE
  retrieve-install-test:
    requires: [deploy-test-server]
    annotations:
      screwdriver.cd/timeout: 120
      screwdriver.cd/cpu: HIGH
      screwdriver.cd/ram: HIGH
    steps:
      - setup: |
          echo DONE
