shared:
  image: docker.io/centos:8
jobs:
  integration-cloud:
    requires: [~commit,~pr]
    annotations:
      screwdriver.cd/timeout: 120
      screwdriver.cd/cpu: HIGH
      screwdriver.cd/ram: HIGH
    secrets:
      - VESPA_CLOUD_USER_KEY
    environment:
      SD_ZIP_ARTIFACTS: true
    steps:
      - setup: |
          export WORK_DIR=$SD_DIND_SHARE_PATH
          export RESOURCES_DIR=$(pwd)/vespa/resources
      - install-python: |
          dnf install -y python38-pip
          python3 -m pip install --upgrade pip
          python3 -m pip install pytest
          python3 -m pip install -e .[full]
      - run-integration-cloud: |
          pytest vespa/test_integration_vespa_cloud.py -s
