shared:
  image: quay.io/centos/centos:stream8
  environment:
    PYVESPA_VERSION: 0.7
jobs:
  unit-tests:
    requires: [~commit,~pr]
    annotations:
      screwdriver.cd/timeout: 120
      screwdriver.cd/cpu: HIGH
      screwdriver.cd/ram: HIGH
      screwdriver.cd/buildPeriodically: H 11 * * *
    steps:
      - setup: |
          export WORK_DIR=$SD_DIND_SHARE_PATH
          export RESOURCES_DIR=$(pwd)/vespa/resources
      - install-python: |
          dnf install -y python38-pip
          dnf install -y --enablerepo=powertools pandoc
          python3 -m pip install --upgrade pip
          python3 -m pip install pytest notebook nbconvert
          python3 -m pip install -e .[full]
          python3 -m pip install -r docs/sphinx/source/requirements.txt
          python3 -m pip install -r docs/sphinx/source/notebook_requirements.txt
      - run-doc-linkcheck: |
          sphinx-build -E -b linkcheck docs/sphinx/source docs/sphinx/build
          sphinx-build -E docs/sphinx/source docs/sphinx/build
          rm -fr docs/sphinx/build
      - run-doc-tests: |
          pytest --doctest-modules --ignore-glob=vespa/test_*.py
      - run-unit-tests: |
          pytest --ignore-glob=vespa/test_integration*.py

  integration-except-cloud:
    requires: [~commit,~pr]
    annotations:
      screwdriver.cd/timeout: 120
      screwdriver.cd/cpu: HIGH
      screwdriver.cd/ram: HIGH
      screwdriver.cd/dockerEnabled: true
      screwdriver.cd/dockerCpu: TURBO
      screwdriver.cd/dockerRam: TURBO
      screwdriver.cd/buildPeriodically: H 11 * * *
    steps:
      - setup: |
          export WORK_DIR=$SD_DIND_SHARE_PATH
          export RESOURCES_DIR=$(pwd)/vespa/resources
      - install-docker: |
          dnf install -y dnf-plugins-core
          dnf config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
          dnf install -y docker-ce-cli
          docker system info
          ls -la $SD_DIND_SHARE_PATH
      - install-python: |
          dnf install -y python38-pip
          python3 -m pip install --upgrade pip
          python3 -m pip install pytest
          python3 -m pip install -e .[full]
      - run-integration-running-instance: |
          pytest vespa/test_integration_running_instance.py -s -v
      - run-integration-docker: |
          pytest vespa/test_integration_docker.py -s -v

  notebooks-except-cloud:
    requires: [~commit,~pr]
    annotations:
      screwdriver.cd/timeout: 120
      screwdriver.cd/cpu: HIGH
      screwdriver.cd/ram: HIGH
      screwdriver.cd/dockerEnabled: true
      screwdriver.cd/dockerCpu: TURBO
      screwdriver.cd/dockerRam: TURBO
      screwdriver.cd/buildPeriodically: H 11 * * *
    steps:
      - setup: |
          dnf install -y git
          export WORK_DIR=$SD_DIND_SHARE_PATH
          export RESOURCES_DIR=$(pwd)/vespa/resources
      - install-docker: |
          dnf install -y dnf-plugins-core
          dnf config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
          dnf install -y docker-ce-cli
          docker system info
          ls -la $SD_DIND_SHARE_PATH
      - install-python: |
          dnf install -y python38-pip
          python3 -m pip install --upgrade pip
          python3 -m pip install pytest notebook nbconvert runnb
          python3 -m pip install -e .[full]
          python3 -m pip install -r docs/sphinx/source/requirements.txt
          python3 -m pip install -r docs/sphinx/source/notebook_requirements.txt
      - run-notebooks-except-cloud-related: |
          #
          # Exclude non-testable notebooks below
          #
          dnf install -y tree
          echo "All non-cloud notebooks:"
          find docs -name '*.ipynb' ! -name '*cloud*.ipynb'
          for notebook in `find docs/sphinx/source -name '*.ipynb' -and \
            ! -name '*cloud*.ipynb' -and \
            ! -path '*/.ipynb_checkpoints/*' -and \
            ! -name 'image-search-scratch.ipynb'`; \
            do echo -e "**********\n*** Running $notebook ***\n**********"; \
            runnb --allow-not-trusted $notebook || exit 1;\
          done

  integration-cloud:
    requires: [~commit]
    annotations:
      screwdriver.cd/timeout: 120
      screwdriver.cd/cpu: HIGH
      screwdriver.cd/ram: HIGH
      screwdriver.cd/buildPeriodically: H 11 * * *
    secrets:
      - VESPA_CLOUD_USER_KEY
    environment:
      SD_ZIP_ARTIFACTS: true
    steps:
      - setup: |
          export WORK_DIR=$SD_DIND_SHARE_PATH
          export RESOURCES_DIR=$(pwd)/vespa/resources
      - install-python: |
          dnf install -y python38-pip
          python3 -m pip install --upgrade pip
          python3 -m pip install pytest
          python3 -m pip install -e .[full]
      - run-integration-cloud: |
          pytest vespa/test_integration_vespa_cloud.py -s -v

  notebooks-cloud:
    requires: [integration-cloud]
    annotations:
      screwdriver.cd/timeout: 120
      screwdriver.cd/cpu: HIGH
      screwdriver.cd/ram: HIGH
    secrets:
      - VESPA_CLOUD_USER_KEY
    environment:
      SD_ZIP_ARTIFACTS: true
    steps:
      - setup: |
          export WORK_DIR=$SD_DIND_SHARE_PATH
          export RESOURCES_DIR=$(pwd)/vespa/resources
      - install-python: |
          dnf install -y python38-pip
          python3 -m pip install --upgrade pip
          python3 -m pip install pytest notebook nbconvert runnb
          python3 -m pip install -e .[full]
          python3 -m pip install -r docs/sphinx/source/requirements.txt
          python3 -m pip install -r docs/sphinx/source/notebook_requirements.txt
      - run-notebooks-cloud-related: |
          find docs -name '*cloud*.ipynb'
          find docs -name '*cloud*.ipynb' -exec jupyter nbconvert --to notebook --ExecutePreprocessor.timeout=600 --execute {} +
          find docs -name '*.nbconvert.ipynb' -exec rm {} + 

  deploy-test-server:
    requires: [unit-tests, integration-except-cloud, notebooks-except-cloud, notebooks-cloud]
    annotations:
      screwdriver.cd/timeout: 120
      screwdriver.cd/cpu: HIGH
      screwdriver.cd/ram: HIGH
    secrets:
      - TEST_PYPI_TOKEN
    steps:
      - install-python: |
          dnf install -y python38-pip
          python3 -m pip install --upgrade pip
          python3 -m pip install twine wheel
      - build: |
          python3 setup.py bdist_wheel
      - publish: |
          python3 -m twine upload --repository testpypi dist/* -u __token__ -p $TEST_PYPI_TOKEN
      - sleep: |
          sleep 300 # sleep to give time for latest version to show on test pypi index

  retrieve-install-test:
    requires: [deploy-test-server]
    annotations:
      screwdriver.cd/timeout: 120
      screwdriver.cd/cpu: HIGH
      screwdriver.cd/ram: HIGH
    steps:
      - setup: |
          export RESOURCES_DIR=$(pwd)/vespa/resources
      - install-python: |
          dnf install -y python38-pip
          python3 -m pip install --upgrade pip
          python3 -m pip install pytest
      - install-package: |
          python3 -m pip cache purge
          python3 -m pip install --no-cache-dir --no-cache --quiet \
            --index-url https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple \
            -Iv pyvespa[full]==$PYVESPA_VERSION.$SD_EVENT_ID 2>&1 | tee $SD_ARTIFACTS_DIR/mylogfile.txt
      - test-package: |
          pytest --ignore-glob=vespa/test_integration*.py -s -v
